Map<String, String> arabic = {
  'CATEGORIES': 'الفئات',
  'TRENDY_COLLECTIONS': 'مجموعات عصرية',
  'FLASH_SALE': 'بيع سريع',
  'SEE_ALL': 'رؤية الكل',
  'NEW': 'جديد',
  'HOME': 'الصفحة الرئيسية',
  'CATEGORY': 'الفئة',
  'WISHLIST': 'قائمة الرغبات',
  'PROFILE': 'الملف الشخصي',
  'MEN': 'رجال',
  'WOMEN': 'نساء',
  'KIDS': 'أطفال',
  'SPORTS': 'رياضات',
  'SALE_AND_OFFER': 'البيع والعروض',
  'SING_IN_TO_SEE_YOUR_INFO': 'تسجيل الدخول لرؤية معلوماتك',
  'Sing In': 'تسجيل الدخول',
  'Sign in to continue shopping': 'تسجيل الدخول لمتابعة التسوق',
  'Password': 'كلمة المرور',
  'Forgot Password': 'نسيت كلمة المرور',
  'Don\'t have an account?': 'ليس لديك حساب؟',
  'Remember me': 'تذكرني',
  'Sign Up': 'التسجيل',
  'Email': 'البريد الإلكتروني',
  'Phone': 'الهاتف',
  '*Use Phone Instead': '*استخدم الهاتف بدلاً من ذلك',
  '*Use Email Instead': '*استخدم البريد الإلكتروني بدلاً من ذلك',
  'Name': 'الاسم',
  'Already have an account?': 'هل لديك حساب بالفعل؟',
  'Welcome Back': 'مرحبًا مرة أخرى',
  'Welcome Back, ': 'مرحبًا مرة أخرى، ',
  'MY_ACCOUNT': 'حسابي',
  'ORDER_HISTORY': 'تاريخ الطلبات',
  'RETURN_ORDERS': 'العودة للطلبات',
  'CHANGE_PASSWORD': 'تغيير كلمة المرور',
  'EDIT_PROFILE': 'تحرير الملف الشخصي',
  'ADDRESSES': 'العناوين',
  'Terms & Conditions': 'الشروط والأحكام',
  'Privacy Policy': 'سياسة الخصوصية',
  'CONTACT_US': 'اتصل بنا',
  'About Us': 'معلومات عنا',
  'LOGOUT': 'تسجيل الخروج',
  'Cookies Policy': 'سياسة الكوكيز',
  'Size Charts': 'جداول الحجم',
  'Shipping': 'الشحن',
  'Return & Exchange': 'الإرجاع والتبادل',
  'Help': 'المساعدة',
  'TOTAL_ORDERS': 'مجموع الطلبات',
  'TOTAL_COMPLETED': 'مجموع المكتملة',
  'TOTAL_RETURNED': 'مجموع المرجعة',
  'WALLET_BALANCE': 'رصيد المحفظة',
  'CHANGE_LANGUAGE': 'تغيير اللغة',
  'CHOOSE_SIZE': 'اختر الحجم:',
  'CHOOSE_COLOR': 'اختر اللون:',
  'QUANTITY': 'الكمية:',
  'FAVORITE': 'المفضلة',
  'ADD_TO_CART': 'أضف إلى السلة',
  'SHIPPING_AND_RETURN': 'الشحن والإرجاع',
  'REVIEW': 'مراجعة',
  'DETAILS': 'تفاصيل',
  'PRODUCT_DTAILS': 'تفاصيل المنتج',
  'RELATED_PRODUCTS': 'منتجات ذات صلة',
  'PROFILE_IMAGE_SAVED_SUCCESSFULLY': 'تم حفظ صورة الملف الشخصي بنجاح',
  'SUCCESS': 'نجاح',
  'ERROR': 'خطأ',
  'Press back again to exit.': 'اضغط مرة أخرى للخروج.',
  'Home': 'الصفحة الرئيسية',
  'Category': 'الفئة',
  'Wishlist': 'قائمة الرغبات',
  'Profile': 'الملف الشخصي',
  'Address': 'العنوان',
  'Add New Address': 'إضافة عنوان جديد',
  'Full Name': 'الاسم الكامل',
  'Zip Code': 'الرمز البريدي',
  'Street Address': 'عنوان الشارع',
  'Add Address': 'إضافة عنوان',
  'Cancel': 'إلغاء',
  'Update Address': 'تحديث العنوان',
  'Are you sure you want to delete?': 'هل أنت متأكد أنك تريد الحذف؟',
  'Delete': 'حذف',
  'Change Password': 'تغيير كلمة المرور',
  'Old Password': 'كلمة المرور القديمة',
  'PLEASE_TYPE_OLD_PASSWORD': 'الرجاء كتابة كلمة المرور القديمة',
  'PLEASE_TYPE_NEW_PASSWORD': 'الرجاء كتابة كلمة المرور الجديدة',
  'New Password': 'كلمة المرور الجديدة',
  'Confirm Password': 'تأكيد كلمة المرور',
  'PLEASE_TYPE_CONFIRM_PASSWORD': 'الرجاء كتابة تأكيد كلمة المرور',
  'PASSWORD_NOT_MATCHED': 'كلمة المرور غير متطابقة',
  'Save Changes': 'حفظ التغييرات',
  'Edit Profile': 'تحرير الملف الشخصي',
  'PLEASE_TYPE_Name': 'الرجاء كتابة اسمك الكامل',
  'PLEASE_TYPE_EMAIL': 'الرجاء كتابة البريد الإلكتروني',
  'PLEASE_TYPE_PHONE_NUMBER': 'الرجاء كتابة رقم الهاتف',
  'IMAGE_SHOULD_BE_LESS_THAN_2MB': 'يجب أن يكون حجم الصورة أقل من 2 ميجابايت',
  'SOMETHING_WRONG': 'حدث خطأ ما',
  'PROFILE_UPDATE_SUCCESSFULLY': 'تم تحديث الملف الشخصي بنجاح',
  'PASSWORD_UPDATE_SUCCESSFULLY': 'تم تحديث كلمة المرور بنجاح',
  'PLEASE_ENTER_VALID_INPUT': 'الرجاء إدخال قيم صحيحة',
  'Verify Email': 'تحقق من البريد الإلكتروني',
  'Verify Number': 'تحقق من الرقم',
  'Enter OTP': 'أدخل رمز التحقق',
  'If you didn\'t receive a code!': 'إذا لم تستلم رمزًا!',
  ' Resend': 'إعادة الإرسال',
  'Verify': 'التحقق',
  'Back to sign in': 'العودة إلى تسجيل الدخول',
  'Get OTP': 'الحصول على رمز التحقق',
  'Reset Password': 'إعادة تعيين كلمة المرور',
  'Password Not Matched': 'كلمة المرور غير متطابقة',
  'Submit': 'إرسال',
  'Popular Brands': 'العلامات التجارية الشهيرة',
  'Explore All Products': 'استكشاف جميع المنتجات',
  'Empty Wishlist': 'قائمة الرغبات فارغة',
  'Search': 'البحث',
  'Product added to cart': 'تمت إضافة المنتج إلى السلة',
  'Product Details': 'تفاصيل المنتج',
  'No Review': 'لا توجد مراجعة',
  'No Shipping & Return Policy': 'لا يوجد سياسة شحن وإرجاع',
  'VIDEOS': 'فيديوهات',
  'Product Videos': 'فيديوهات المنتج',
  'Shipping & Return': 'الشحن والإرجاع',
  'Product Reviews': 'مراجعات المنتج',
  'Order Details': 'تفاصيل الطلب',
  'Thank You': 'شكراً لك',
  'Your Order status is as follows': 'حالة طلبك كما يلي',
  'Order ID: ': 'رقم الطلب: ',
  'Order Canceled': 'تم إلغاء الطلب',
  'Order Rejected': 'تم رفض الطلب',
  'Order ID:': 'رقم الطلب:',
  'Order Date:': 'تاريخ الطلب:',
  'Order Status:': 'حالة الطلب:',
  'Payment Status:': 'حالة الدفع:',
  'Payment Type:': 'نوع الدفع:',
  'Pending': 'قيد الانتظار',
  'Confirmed': 'تم التأكيد',
  'On The Way': 'في الطريق',
  'Delivered': 'تم التوصيل',
  'Canceled': 'تم الإلغاء',
  'Rejected': 'تم الرفض',
  'Paid': 'تم الدفع',
  'Unpaid': 'لم يتم الدفع',
  'Name:': 'الاسم:',
  'Phone:': 'الهاتف:',
  'Email:': 'البريد الإلكتروني:',
  'Outlet Address:': 'عنوان المتجر:',
  'Shipping Address:': 'عنوان الشحن:',
  'Billing Address:': 'عنوان الفاتورة:',
  'Order Summary': 'ملخص الطلب',
  'Subtotal': 'المجموع الفرعي',
  'Tax': 'الضريبة',
  'Shipping Charge': 'رسوم الشحن',
  'Discount': 'الخصم',
  'Download Receipt': 'تحميل الفاتورة',
  'Return Request': 'طلب الإرجاع',
  'Cancel Order': 'إلغاء الطلب',
  'Tel:': 'الهاتف:',
  'Order#': 'رقم الطلب#',
  'Qty': 'الكمية',
  'Item Description': 'وصف السلعة',
  'Price': 'السعر',
  'Total': 'المجموع',
  'Order Type': 'نوع الطلب',
  'Order Date Time': 'تاريخ ووقت الطلب',
  'Delivery': 'التوصيل',
  'Pickup': 'الاستلام',
  'POS': 'POS',
  'Customer': 'العميل',
  'Powered by': 'مشغل بواسطة',
  'Print Invoice': 'طباعة الفاتورة',
  'Edit Review': 'تعديل التقييم',
  'Your Review': 'تقييمك',
  'Review Details': 'تفاصيل التقييم',
  'Please write review details': 'الرجاء كتابة تفاصيل التقييم',
  'Upload Images': 'تحميل الصور',
  'Add Image': 'إضافة صورة',
  'Submit Review': 'إرسال التقييم',
  'Info: ': 'معلومات: ',
  'Product': 'المنتج',
  'Delivery Status: ': 'حالة التوصيل: ',
  'Payment Status: ': 'حالة الدفع: ',
  'Total: ': 'المجموع: ',
  'Qty:': 'الكمية:',
  'Write Review': 'كتابة تقييم',
  'Price: ': 'السعر: ',
  'Return Status: ': 'حالة الإرجاع: ',
  'Accepted': 'تم القبول',
  'Return Order Details': 'تفاصيل طلب الإرجاع',
  'Return Reason': 'سبب الإرجاع',
  'Return Note': 'ملاحظة الإرجاع',
  'Attachment': 'المرفقات',
  'Return Response': 'رد الإرجاع',
  'Request Return': 'طلب الإرجاع',
  'Please select return reason': 'الرجاء اختيار سبب الإرجاع',
  'Please write return note': 'الرجاء كتابة ملاحظة الإرجاع',
  'Please select an item': 'الرجاء اختيار عنصر',
  'Order Canceled Successfully!': 'تم إلغاء الطلب بنجاح!',
  'Return request submitted successfully!': 'تم تقديم طلب الإرجاع بنجاح!',
  'Return request not submitted': 'لم يتم تقديم طلب الإرجاع',
  'Review submitted successfully!': 'تم تقديم التقييم بنجاح!',
  'Review not submitted': 'لم يتم تقديم التقييم',
  'Review Updated successfully!': 'تم تحديث التقييم بنجاح!',
  'Address Added Successfully!': 'تمت إضافة العنوان بنجاح!',
  'ADDRESS_UPDATED_SUCCESSFULLY': 'تم تحديث العنوان بنجاح!',
  'ADDRESS_DELETED_SUCCESSFULLY': 'تم حذف العنوان بنجاح!',
  'Shipping Information': 'معلومات الشحن',
  'Pick Up': 'الاستلام',
  'Shipping Address': 'عنوان الشحن',
  'Edit': 'تحرير',
  'Add': 'إضافة',
  'Save shipping address as a billing address.':
      'احفظ عنوان الشحن كعنوان فوترة.',
  'Apply Promo, Coupon or Voucher': 'قدّم العرض الترويجي أو الكوبون أو القسيمة',
  'Coupon Applied': 'تم تطبيق الكوبون',
  'Get discount with your order': 'احصل على خصم مع طلبك',
  'You saved': 'لقد قمت بالحفظ',
  'Shipping & billing addresses are required.':
      'العناوين الشحن والفوترة مطلوبة.',
  'Outlet is required.': 'المخرج مطلوب.',
  'Save & Pay': 'احفظ وادفع',
  'Order': 'الطلب',
  'On the': 'في الطريق',
  'Way': 'طريق',
  'Stock is over': 'المخزون انتهى',
  'Shopping Cart': 'عربة التسوق',
  'Your cart is empty': 'عربتك فارغة',
  'Proceed to Checkout': 'تابع إلى الدفع',
  'Shipping, Taxes & Discount Calculate at Checkout':
      'حساب تكلفة الشحن والضرائب والخصم عند الدفع',
  'Remove': 'إزالة',
  'Enter Code': 'أدخل الرمز',
  'Please enter a valid coupon': 'الرجاء إدخال كوبون صالح',
  'Promo, Coupon or Voucher': 'الترويج، الكوبون أو القسيمة',
  'Apply': 'قدّم',
  'Coupon & Vouchers for you': 'كوبونات وقسائم لك',
  'Filter & Sorting': 'تصفية وفرز',
  'Product Type': 'نوع المنتج',
  'Size': 'الحجم',
  'Color': 'اللون',
  'Brands': 'العلامات التجارية',
  'Sort By': 'الفرز حسب',
  'Newest': 'الأحدث',
  'Price Low To High': 'السعر من الأدنى إلى الأعلى',
  'Price High To Low': 'السعر من الأعلى إلى الأدنى',
  'Top Rated': 'الأعلى تقييمًا',
  'See All': 'عرض الكل',
  'Payment Information': 'معلومات الدفع',
  'Select Payment Method': 'اختر طريقة الدفع',
  'Confirm Order': 'تأكيد الطلب',
  'Products Found': 'المنتجات الموجودة',
  'Flash Sale': 'بيع سريع',
  'New': 'جديد',
  'Reviews': 'التقييمات',
  ' Products Found': 'المنتجات الموجودة ',
  'Validation Error.': 'خطأ في التحقق',
  'Credentials errors.': 'أخطاء في الاعتمادات',
  'Invalid credentials or you are blocked': 'اعتمادات غير صالحة أو تم حظرك',
  'Role errors.': 'أخطاء في الدور',
  'Role does not exist.': 'الدور غير موجود',
  'Login Successfully.': 'تسجيل الدخول بنجاح',
  'Logged Out Successfully.': 'تم تسجيل الخروج بنجاح',
  'Invalid Api Key.': 'مفتاح API غير صالح',
  'User not match.': 'المستخدم غير متطابق',
  'Something wrong.': 'هناك خطأ ما',
  'The permission is denied.': 'تم رفض الإذن',
  'Product not match.': 'المنتج غير متطابق',
  'The product already added in another offer. When the offer is end then you can add this item again.':
      'تمت إضافة المنتج بالفعل في عرض آخر. عند انتهاء العرض، يمكنك إضافة هذا العنصر مرة أخرى.',
  'The minimum order amount is ': 'الحد الأدنى للمبلغ في الطلب هو ',
  'The coupon time is expired': 'انتهت صلاحية القسيمة',
  'The coupon does not exist': 'القسيمة غير موجودة',
  'The code is invalid.': 'الرمز غير صالح',
  'The code is expired.': 'انتهت صلاحية الرمز',
  'Now you can reset your password.':
      'الآن يمكنك إعادة تعيين كلمة المرور الخاصة بك',
  'Please check your email for the code.':
      'يرجى التحقق من بريدك الإلكتروني للحصول على الرمز',
  'Please check your phone for the code.':
      'يرجى التحقق من هاتفك للحصول على الرمز',
  'The token created fail.': 'فشل إنشاء الرمز',
  'This email does not exist.': 'هذا البريد الإلكتروني غير موجود',
  'This phone does not exist.': 'هذا الهاتف غير موجود',
  'This User does not exist.': 'هذا المستخدم غير موجود',
  'This phone already exists.': 'هذا الهاتف موجود بالفعل',
  'The OTP verify is successfully.': 'تم التحقق بنجاح من OTP',
  'The User verify is successfully.': 'تم التحقق بنجاح من المستخدم',
  'Register Successfully.': 'تم التسجيل بنجاح',
  'Your password reset Successfully.':
      'تم إعادة تعيين كلمة المرور الخاصة بك بنجاح',
  'Select your payment method.': 'حدد طريقة الدفع الخاصة بك',
  'Your payment has been successfully processed.': 'تمت معالجة دفعتك بنجاح',
  'The payment is canceled.': 'تم إلغاء الدفع',
  'The payment gateway is disabled': 'تم تعطيل بوابة الدفع',
  'The token saved successfully.': 'تم حفظ الرمز بنجاح',
  'The token is invalid.': 'الرمز غير صالح',
  'The order already accepted.': 'الطلب تم قبوله بالفعل',
  'The order already confirmed.': 'الطلب تم تأكيده بالفعل',
  'This feature is disabled for the demo.':
      'تم تعطيل هذه الميزة للعرض التوضيحي',
  'Time slots already exist.': 'فترات الوقت موجودة بالفعل',
  'This attribute is invalid. Create attribute or attribute option.':
      'هذا السمة غير صالحة. قم بإنشاء سمة أو خيار سمة.',
  'This price amount is invalid.': 'هذا المبلغ السعري غير صالح',
  'This product attribute id is invalid.': 'هوية سمة المنتج هذه غير صالحة',
  'This product attribute option id is invalid.':
      'هوية خيار سمة المنتج هذه غير صالحة',
  'The sku has already been taken.': 'تم أخذ هذا SKU بالفعل',
  'Cannot remove this resource permanently. It is related to another resource.':
      'لا يمكن إزالة هذا المورد بشكل دائم. إنه مرتبط بمورد آخر.',
  'The sku field is required.': 'حقل SKU مطلوب',
  'The email or phone field is required.':
      'حقل البريد الإلكتروني أو الهاتف مطلوب',
  'The Country has already been taken.': 'تم أخذ البلد بالفعل',
  'The tax field is required for all products.':
      'حقل الضريبة مطلوب لجميع المنتجات',
  'The quantity field is required for all products.':
      'حقل الكمية مطلوب لجميع المنتجات',
  'The product field is required.': 'حقل المنتج مطلوب',
  'The unit cost field is required for all products.':
      'حقل تكلفة الوحدة مطلوب لجميع المنتجات',
  'The total product unit cost is invalid.':
      'إجمالي تكلفة الوحدة للمنتج غير صالح',
  'The supplier is invalid.': 'المورد غير صالح',
  'The status is invalid.': 'الحالة غير صالحة',
  'The Return request already exists.': 'طلب الإرجاع موجود بالفعل',
  'The last outlet cannot be deleted.': 'لا يمكن حذف آخر منفذ',
  'Email Send Successfully.': 'تم إرسال البريد الإلكتروني بنجاح',
  'The amount is invalid.': 'المبلغ غير صالح',
  'Available:': 'متاح:',
  'Piece': 'قطعة',
  'Search Results': 'نتائج البحث',
  'Order Type:': 'نوع الطلب:',
  'Product Description': 'وصف المنتج',
  'Outlet': 'المنفذ',
  'Enter Valid Email Address': 'أدخل عنوان بريد إلكتروني صالح',
  'Thank you for your order!': 'شكرًا لطلبك!',
  'Your order is confirmed.': 'تم تأكيد طلبك.',
  'Go to order details': 'الانتقال إلى تفاصيل الطلب',
  'Your payment has been confirmed': 'تم تأكيد دفعتك',
  'Payment Failed': 'فشلت عملية الدفع',
  'Are you sure want to close this payment session?':
      'هل أنت متأكد أنك تريد إغلاق هذه الجلسة الدفع؟',
  'Yes': 'نعم',
  'Retry': 'إعادة المحاولة',
  'Please select payment method.': 'الرجاء اختيار طريقة الدفع.',
  "Billing Address": "عنوان الفواتير",
  'Insufficient balance': 'رصيد غير كافٍ',
  'Most Popular': 'الأكثر شيوعاً',
  'Added to Wishlist': 'تمت الإضافة إلى قائمة الرغبات',
  'Removed from Wishlist': 'تمت إزالة من قائمة الرغبات',
  'DELETE_ACCOUNT': 'حذف الحساب'
};
