Map<String, String> bangla = {
  'CATEGORIES': 'বিভাগসমূহ',
  'TRENDY_COLLECTIONS': 'ট্রেন্ডি সংগ্রহ',
  'FLASH_SALE': 'ফ্ল্যাশ বিক্রয়',
  'SEE_ALL': 'সব দেখুন',
  'NEW': 'নতুন',
  'HOME': 'হোম',
  'CATEGORY': 'বিভাগ',
  'WISHLIST': 'ইচ্ছেতালিকা',
  'PROFILE': 'প্রোফাইল',
  'MEN': 'পুরুষ',
  'WOMEN': 'মহিলা',
  'KIDS': 'শিশু',
  'SPORTS': 'খেলা',
  'SALE_AND_OFFER': 'বিক্রয় এবং অফার',
  'SING_IN_TO_SEE_YOUR_INFO': 'আপনার তথ্য দেখতে সাইন ইন করুন',
  'Sing In': 'সাইন ইন',
  'Sign in to continue shopping': 'এখানে কেনাকেনি চালানোর জন্য সাইন ইন করুন',
  'Password': 'পাসওয়ার্ড',
  'Forgot Password': 'পাসওয়ার্ড ভুলে গেছেন?',
  'Don\'t have an account?': 'একটি অ্যাকাউন্ট আছে না?',
  'Remember me': 'আমাকে মনে রাখুন',
  'Sign Up': 'সাইন আপ',
  'Email': 'ইমেইল',
  'Phone': 'ফোন',
  '*Use Phone Instead': '*ফোনের পরিবর্তে ব্যবহার করুন',
  '*Use Email Instead': '*ইমেইলের পরিবর্তে ব্যবহার করুন',
  'Name': 'নাম',
  'Already have an account?': 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
  'Welcome Back': 'স্বাগতম ফিরে',
  'Welcome Back, ': 'স্বাগতম ফিরে, ',
  'MY_ACCOUNT': 'আমার অ্যাকাউন্ট',
  'ORDER_HISTORY': 'অর্ডার ইতিহাস',
  'RETURN_ORDERS': 'ফেরত অর্ডার',
  'CHANGE_PASSWORD': 'পাসওয়ার্ড পরিবর্তন করুন',
  'EDIT_PROFILE': 'প্রোফাইল সম্পাদনা করুন',
  'ADDRESSES': 'ঠিকানা',
  'Terms & Conditions': 'শর্তাবলী এবং শর্তাদি',
  'Privacy Policy': 'গোপনীয়তা নীতি',
  'CONTACT_US': 'যোগাযোগ করুন',
  'About Us': 'আমাদের সম্পর্কে',
  'LOGOUT': 'লগআউট',
  'Cookies Policy': 'কুকিজ নীতি',
  'Size Charts': 'আকার চার্ট',
  'Shipping': 'শিপিং',
  'Return & Exchange': 'ফেরত এবং বিনিময়',
  'Help': 'সাহায্য',
  'TOTAL_ORDERS': 'মোট অর্ডার',
  'TOTAL_COMPLETED': 'মোট সম্পন্ন',
  'TOTAL_RETURNED': 'মোট ফেরত দেওয়া',
  'WALLET_BALANCE': 'ওয়ালেট ব্যালেন্স',
  'CHANGE_LANGUAGE': 'ভাষা পরিবর্তন করুন',
  'CHOOSE_SIZE': 'আকার চয়ন করুন:',
  'CHOOSE_COLOR': 'রঙ চয়ন করুন:',
  'QUANTITY': 'পরিমাণ:',
  'FAVORITE': 'প্রিয়',
  'ADD_TO_CART': 'কার্টে যোগ করুন',
  'SHIPPING_AND_RETURN': 'শিপিং এবং ফেরত',
  'REVIEW': 'পর্যালোচনা',
  'DETAILS': 'বিশদ',
  'PRODUCT_DTAILS': 'পণ্যের বিবরণ',
  'RELATED_PRODUCTS': 'সম্পর্কিত পণ্য',
  'PROFILE_IMAGE_SAVED_SUCCESSFULLY': 'প্রোফাইল ছবি সফলভাবে সংরক্ষণ করা হয়েছে',
  'SUCCESS': 'সাফল্য',
  'ERROR': 'ত্রুটি',
  'Press back again to exit.': 'পুনরায় বাচাই করতে পৃষ্ঠপুটি চাপুন',
  'Home': 'হোম',
  'Category': 'বিভাগ',
  'Wishlist': 'ইচ্ছেতালিকা',
  'Profile': 'প্রোফাইল',
  'Address': 'ঠিকানা',
  'Add New Address': 'নতুন ঠিকানা যোগ করুন',
  'Full Name': 'পুরো নাম',
  'Zip Code': 'জিপ কোড',
  'Street Address': 'রাস্তার ঠিকানা',
  'Add Address': 'ঠিকানা যোগ করুন',
  'Cancel': 'বাতিল',
  'Update Address': 'ঠিকানা আপডেট করুন',
  'Are you sure you want to delete?': 'আপনি কি নিশ্চিত যে আপনি মুছতে চান?',
  'Delete': 'মুছে ফেলুন',
  'Change Password': 'পাসওয়ার্ড পরিবর্তন করুন',
  'Old Password': 'পুরাতন পাসওয়ার্ড',
  'PLEASE_TYPE_OLD_PASSWORD': 'দয়া করে পুরাতন পাসওয়ার্ড টাইপ করুন',
  'PLEASE_TYPE_NEW_PASSWORD': 'দয়া করে নতুন পাসওয়ার্ড টাইপ করুন',
  'New Password': 'নতুন পাসওয়ার্ড',
  'Confirm Password': 'পাসওয়ার্ড নিশ্চিত করুন',
  'PLEASE_TYPE_CONFIRM_PASSWORD': 'দয়া করে পাসওয়ার্ড নিশ্চিত করুন',
  'PASSWORD_NOT_MATCHED': 'পাসওয়ার্ড মেলেনি',
  'Save Changes': 'পরিবর্তন সংরক্ষণ করুন',
  'Edit Profile': 'প্রোফাইল সম্পাদনা করুন',
  'PLEASE_TYPE_Name': 'দয়া করে আপনার পুরো নাম টাইপ করুন',
  'PLEASE_TYPE_EMAIL': 'ইমেল টাইপ করুন',
  'PLEASE_TYPE_PHONE_NUMBER': 'ফোন নম্বর টাইপ করুন',
  'IMAGE_SHOULD_BE_LESS_THAN_2MB': 'চিত্র 2 MB-এর কম হতে হবে',
  'SOMETHING_WRONG': 'কিছু ভুল হয়েছে',
  'PROFILE_UPDATE_SUCCESSFULLY': 'প্রোফাইল সফলভাবে আপডেট হয়েছে',
  'PASSWORD_UPDATE_SUCCESSFULLY': 'পাসওয়ার্ড সফলভাবে আপডেট হয়েছে',
  'PLEASE_ENTER_VALID_INPUT': 'দয়া করে বৈধ ইনপুট দিন',
  'Verify Email': 'ইমেল যাচাই করুন',
  'Verify Number': 'নম্বর যাচাই করুন',
  'Enter OTP': 'OTP দিন',
  'If you didn\'t receive a code!': 'আপনি কোড পাচ্ছেন না!',
  'Resend': 'পুনরায় পাঠান',
  'Verify': 'যাচাই করুন',
  'Back to sign in': 'সাইন ইনে ফিরে যান',
  'Get OTP': 'OTP পান',
  'Reset Password': 'পাসওয়ার্ড রিসেট',
  'Password Not Matched': 'পাসওয়ার্ড মেলেনি',
  'Submit': 'জমা দিন',
  'Popular Brands': 'জনপ্রিয় ব্র্যান্ড',
  'Explore All Products': 'সমস্ত পণ্য অন্বেষণ করুন',
  'Empty Wishlist': 'খালি ইচ্ছেতালিকা',
  'Search': 'অনুসন্ধান',
  'Product added to cart': 'পণ্য কার্টে যোগ হয়েছে',
  'Product Details': 'পণ্যের বিবরণ',
  'No Review': 'কোন পর্যালোচনা নেই',
  'No Shipping & Return Policy': 'কোন শিপিং এবং রিটার্ন নীতি নেই',
  'VIDEOS': 'ভিডিও',
  'Product Videos': 'পণ্য ভিডিও',
  'Shipping & Return': 'শিপিং এবং রিটার্ন',
  'Product Reviews': 'পণ্য পর্যালোচনা',
  'Order Details': 'অর্ডার বিবরণ',
  'Thank You': 'ধন্যবাদ',
  'Your Order status is as follows': 'আপনার অর্ডার স্থিতি নিম্নলিখিতভাবে',
  'Order ID: ': 'অর্ডার আইডি: ',
  'Order Canceled': 'অর্ডার বাতিল',
  'Order Rejected': 'অর্ডার প্রত্যাখ্যান',
  'Order ID:': 'অর্ডার আইডি:',
  'Order Date:': 'অর্ডারের তারিখ:',
  'Order Status:': 'অর্ডারের স্থিতি:',
  'Payment Status:': 'পেমেন্ট স্থিতি:',
  'Payment Type:': 'পেমেন্ট ধরণ:',
  'Pending': 'বিচারাধীন',
  'Confirmed': 'নিশ্চিত',
  'On The Way': 'মার্গে',
  'Delivered': 'ডেলিভারি হয়েছে',
  'Canceled': 'বাতিল',
  'Rejected': 'প্রত্যাখ্যান',
  'Paid': 'পরিশোধিত',
  'Unpaid': 'অপরিশোধিত',
  'Name:': 'নাম:',
  'Phone:': 'ফোন:',
  'Email:': 'ইমেইল:',
  'Outlet Address:': 'আউটলেট ঠিকানা:',
  'Shipping Address:': 'শিপিং ঠিকানা:',
  'Billing Address:': 'বিলিং ঠিকানা:',
  'Order Summary': 'অর্ডার সংক্ষেপ',
  'Subtotal': 'উপ-মোট',
  'Tax': 'কর',
  'Shipping Charge': 'শিপিং চার্জ',
  'Discount': 'ডিসকাউন্ট',
  'Download Receipt': 'রসিদ ডাউনলোড করুন',
  'Return Request': 'ফেরতের অনুরোধ',
  'Cancel Order': 'অর্ডার বাতিল',
  'Tel:': 'টেল:',
  'Order#': 'অর্ডার নম্বর#',
  'Qty': 'পরিমাণ',
  'Item Description': 'আইটেমের বিবরণ',
  'Price': 'মূল্য',
  'Total': 'মোট',
  'Order Type': 'অর্ডারের ধরণ',
  'Order Date Time': 'অর্ডার তারিখ ও সময়',
  'Delivery': 'ডেলিভারি',
  'Pickup': 'পিকআপ',
  'POS': 'পস',
  'Customer': 'গ্রাহক',
  'Powered by': 'দ্বারা প্রচালিত',
  'Print Invoice': 'চালান মুদ্রণ',
  'Edit Review': 'পর্দ্ধান সম্পাদনা',
  'Your Review': 'আপনার পর্দ্ধান',
  'Review Details': 'পর্দ্ধানের বিবরণ',
  'Please write review details': 'অনুগ্রহ করে পর্দ্ধানের বিবরণ লিখুন',
  'Upload Images': 'ছবি আপলোড করুন',
  'Add Image': 'ছবি যোগ করুন',
  'Submit Review': 'পর্দ্ধান জমা দিন',
  'Info: ': 'তথ্য: ',
  'Product': 'পণ্য',
  'Delivery Status: ': 'ডেলিভারির অবস্থা: ',
  'Payment Status: ': 'পেমেন্ট স্থিতি: ',
  'Total: ': 'মোট: ',
  'Qty:': 'পরিমাণ:',
  'Write Review': 'পর্দ্ধান লিখুন',
  'Price: ': 'মূল্য: ',
  'Return Status: ': 'ফেরতের অবস্থা: ',
  'Accepted': 'গৃহীত',
  'Return Order Details': 'ফেরতের অর্ডার বিবরণ',
  'Return Reason': 'ফেরতের কারণ',
  'Return Note': 'ফেরতের নোট',
  'Attachment': 'সংযুক্তি',
  'Return Response': 'ফেরতের প্রতিক্রিয়া',
  'Request Return': 'ফেরতের অনুরোধ',
  'Please select return reason': 'অনুগ্রহ করে ফেরতের কারণ নির্বাচন করুন',
  'Please write return note': 'অনুগ্রহ করে ফেরতের নোট লিখুন',
  'Please select an item': 'অনুগ্রহ করে একটি আইটেম নির্বাচন করুন',
  'Order Canceled Successfully!': 'অর্ডার সফলভাবে বাতিল হয়েছে!',
  'Return request submitted successfully!':
      'ফেরতের অনুরোধ সফলভাবে জমা দেওয়া হয়েছে!',
  'Return request not submitted': 'ফেরতের অনুরোধ জমা দেওয়া হয়নি',
  'Review submitted successfully!': 'পর্দ্ধান সফলভাবে জমা দেওয়া হয়েছে!',
  'Review not submitted': 'পর্দ্ধান জমা দেওয়া হয়নি',
  'Review Updated successfully!': 'পর্দ্ধান সফলভাবে আপডেট হয়েছে!',
  'Address Added Successfully!': 'ঠিকানা সফলভাবে যোগ করা হয়েছে!',
  'ADDRESS_UPDATED_SUCCESSFULLY': 'ঠিকানা সফলভাবে আপডেট হয়েছে!',
  'ADDRESS_DELETED_SUCCESSFULLY': 'ঠিকানা সফলভাবে মুছে ফেলা হয়েছে!',
  'Shipping Information': 'শিপিং তথ্য',
  'Pick Up': 'পিক আপ',
  'Shipping Address': 'শিপিং ঠিকানা',
  'Edit': 'সম্পাদনা',
  'Add': 'যোগ করুন',
  'Save shipping address as a billing address.':
      'বিলিং ঠিকানা হিসেবে শিপিং ঠিকানা সংরক্ষণ করুন।',
  'Apply Promo, Coupon or Voucher': 'প্রোমো, কুপন অথবা ভাউচার প্রয়োগ করুন',
  'Coupon Applied': 'কুপন প্রয়োগ করা হয়েছে',
  'Get discount with your order': 'আপনার অর্ডারে ডিসকাউন্ট পান',
  'You saved': 'আপনি সংরক্ষণ করেছেন',
  'Shipping & billing addresses are required.':
      'শিপিং এবং বিলিং ঠিকানা প্রয়োজন।',
  'Outlet is required.': 'আউটলেট প্রয়োজন।',
  'Save & Pay': 'সংরক্ষণ এবং পরিশোধ করুন',
  'Order': 'অর্ডার',
  'On the': 'উপর',
  'Way': 'পথে',
  'Stock is over': 'স্টক শেষ',
  'Shopping Cart': 'শপিং কার্ট',
  'Your cart is empty': 'আপনার কার্ট খালি',
  'Procced to Checkout': 'চেকআউটে এগিয়ে যান',
  'Shipping, Taxes & Discount Calculate at Checkout':
      'চেকআউটে শিপিং, কর এবং ডিসকাউন্ট হিসেব করুন',
  'Remove': 'মুছে ফেলুন',
  'Enter Code': 'কোড লিখুন',
  'Please enter a valid coupon': 'দয়া করে একটি বৈধ কুপন লিখুন',
  'Promo, Coupon or Voucher': 'প্রোমো, কুপন অথবা ভাউচার',
  'Apply': 'প্রয়োগ করুন',
  'Coupon & Vouchers for you': 'আপনার জন্য কুপন এবং ভাউচার',
  'Filter & Sorting': 'ফিল্টার এবং সরবরাহ',
  'Product Type': 'পণ্যের ধরণ',
  'Size': 'আকার',
  'Color': 'রঙ',
  'Brands': 'ব্র্যান্ড',
  'Sort By': 'ক্রমানুসারে',
  'Newest': 'নতুন',
  'Price Low To High': 'মূল্য কম থেকে বাড়ি',
  'Price High To Low': 'মূল্য বেশি থেকে কম',
  'Top Rated': 'শীর্ষ রেটেড',
  'See All': 'সব দেখুন',
  'Payment Information': 'পেমেন্ট তথ্য',
  'Select Payment Method': 'পেমেন্ট পদ্ধতি চয়ন করুন',
  'Confirm Order': 'অর্ডার নিশ্চিত করুন',
  'Products Found': 'পণ্য পাওয়া গিয়েছে',
  'Flash Sale': 'ফ্ল্যাশ বিক্রয়',
  'New': 'নতুন',
  'Reviews': 'পর্যালোচনাগুলি',
  ' Products Found': ' পণ্য পাওয়া গিয়েছে',
  'Validation Error.': 'যাচাই ত্রুটি',
  'Credentials errors.': 'শংসাপত্র ত্রুটি',
  'Invalid credentials or you are blocked':
      'অবৈধ শংসাপত্র বা আপনি ব্লক করা হয়েছে',
  'Role errors.': 'ভূমিকা ত্রুটি',
  'Role does not exist.': 'ভূমিকা বা অস্তিত্ব নেই',
  'Login Successfully.': 'সফলভাবে লগইন হয়েছে',
  'Logged Out Successfully.': 'সফলভাবে লগআউট হয়েছে',
  'Invalid Api Key.': 'অবৈধ API কী',
  'User not match.': 'ব্যবহারকারী মেলেনি',
  'Something wrong.': 'কিছু ভুল হয়েছে',
  'The permission is denied.': 'অনুমতি প্রত্যাখ্যান',
  'Product not match.': 'পণ্য মেলেনি',
  'The product already added in another offer. When the offer is end then you can add this item again.':
      'পণ্যটি ইতিমধ্যে অন্য অফারে যোগ করা হয়েছে। অফার শেষ হলে আপনি এই আইটেমটি আবার যোগ করতে পারবেন।',
  'The minimum order amount is ': 'সর্বনিম্ন অর্ডার পরিমাণ ',
  'The coupon time is expired': 'কুপনের সময় মেয়াদ উত্তীর্ণ',
  'The coupon does not exist': 'কুপন অস্তিত্ব নেই',
  'The code is invalid.': 'কোড অবৈধ',
  'The code is expired.': 'কোড মেয়াদোত্তীর্ণ',
  'Now you can reset your password.':
      'এখন আপনি আপনার পাসওয়ার্ড রিসেট করতে পারেন',
  'Please check your email for the code.': 'কোডের জন্য আপনার ইমেইল চেক করুন।',
  'Please check your phone for the code.': 'কোডের জন্য আপনার ফোন চেক করুন।',
  'The token created fail.': 'টোকেন তৈরি হয়নি',
  'This email does not exist.': 'এই ইমেইলটি অস্তিত্ব নেই',
  'This phone does not exist.': 'এই ফোনটি অস্তিত্ব নেই',
  'This User does not exist.': 'এই ব্যবহারকারী অস্তিত্ব নেই',
  'This phone already exists.': 'এই ফোনটি ইতিমধ্যে অস্তিত্বে আছে',
  'The OTP verify is successful.': 'OTP যাচাই সফল',
  'The User verify is successful.': 'ব্যবহারকারী যাচাই সফল',
  'Register Successfully.': 'সফলভাবে নিবন্ধন হয়েছে',
  'Your password reset Successfully.': 'আপনার পাসওয়ার্ড সফলভাবে রিসেট হয়েছে',
  'Select your payment method.': 'আপনার পেমেন্ট পদ্ধতি নির্বাচন করুন',
  'Your payment has been successfully processed.':
      'আপনার পেমেন্ট সফলভাবে প্রক্রিয়াজাত করা হয়েছে',
  'The payment is canceled.': 'পেমেন্ট বাতিল করা হয়েছে',
  'The payment gateway is disabled': 'পেমেন্ট গেটওয়ে অক্ষম হয়েছে',
  'The token saved successfully.': 'টোকেন সফলভাবে সংরক্ষিত হয়েছে',
  'The token is invalid.': 'টোকেন অবৈধ',
  'The order already accepted.': 'অর্ডারটি ইতিমধ্যে গৃহীত হয়েছে',
  'The order already confirmed.': 'অর্ডারটি ইতিমধ্যে নিশ্চিত হয়েছে',
  'This feature is disabled for the demo.': 'ডেমো জন্য এই বৈশিষ্ট্যটি অক্ষম',
  'Time slots already exist.': 'সময় স্লট ইতিমধ্যে বিদ্যমান',
  'This attribute is invalid. Create attribute or attribute option.':
      'এই গুণমাধ্যম অবৈধ। গুণমাধ্যম বা গুণমাধ্যম বিকল্প তৈরি করুন।',
  'This price amount is invalid.': 'এই মূল্য পরিমাণটি অবৈধ',
  'This product attribute id is invalid.': 'এই পণ্য গুণমাধ্যম আইডি অবৈধ',
  'This product attribute option id is invalid.':
      'এই পণ্য গুণমাধ্যম বিকল্প আইডি অবৈধ',
  'The sku has already been taken.': 'SKU ইতিমধ্যে নেওয়া হয়েছে',
  'Cannot remove this resource permanently. It is related to another resource.':
      'এই সম্পদ স্থায়ীভাবে অপসারণ করা যাবে না। এটি অন্য একটি সম্পদের সাথে সম্পর্কিত।',
  'The sku field is required.': 'SKU ক্ষেত্রটি প্রয়োজন',
  'The email or phone field is required.': 'ইমেইল বা ফোন ক্ষেত্রটি প্রয়োজন',
  'The Country has already been taken.': 'দেশটি ইতিমধ্যে নেওয়া হয়েছে',
  'The tax field is required for all products.':
      'সমস্ত পণ্যের জন্য কর ক্ষেত্রটি প্রয়োজন',
  'The quantity field is required for all products.':
      'সমস্ত পণ্যের জন্য পরিমাণ ক্ষেত্রটি প্রয়োজন',
  'The product filed is required.': 'পণ্য ক্ষেত্রটি প্রয়োজন',
  'The unit cost field is required for all products.':
      'সমস্ত পণ্যের জন্য একক মূল্য ক্ষেত্রটি প্রয়োজন',
  'The total product unit cost is invalid.': 'সর্বমোট পণ্য একক মূল্য অবৈধ',
  'The supplier is invalid.': 'সরবরাহকারী অবৈধ',
  'The status is invalid.': 'স্থিতি অবৈধ',
  'The Return request already exists.': 'ফেরতের অনুরোধটি ইতিমধ্যে বিদ্যমান',
  'The last outlet cannot be deleted.': 'শেষ আউটলেটটি মুছে ফেলা যাবে না',
  'Email Send Successfully.': 'ইমেইল সফলভাবে পাঠানো হয়েছে',
  'The amount is invalid.': 'মূল্য অবৈধ',
  'Available:': 'উপলব্ধ:',
  'Piece': 'টুকরা',
  'Search Results': 'অনুসন্ধান ফলাফল',
  'Order Type:': 'অর্ডার টাইপ:',
  'Product Description': 'পণ্যের বিবরণ',
  'Outlet': 'আউটলেট',
  'Enter Valid Email Address': 'বৈধ ইমেল ঠিকানা লিখুন',
  'Thank you for your order!': 'আপনার অর্ডারের জন্য ধন্যবাদ!',
  'Your order is confirmed.': 'আপনার অর্ডার নিশ্চিত হয়েছে।',
  'Go to order details': 'অর্ডার বিবরণে যান',
  'Your payment has been confirmed': 'আপনার পেমেন্ট নিশ্চিত হয়েছে',
  'Payment Failed': 'পেমেন্ট ব্যর্থ হয়েছে',
  'Are you sure want to close this payment session?':
      'আপনি কি নিশ্চিত যে আপনি এই পেমেন্ট সেশনটি বন্ধ করতে চান?',
  'Yes': 'হ্যাঁ',
  'Retry': 'পুনরায় চেষ্টা করুন',
  'Please select payment method.': 'অনুগ্রহ করে পেমেন্ট পদ্ধতি নির্বাচন করুন।',
  "Billing Address": "বিলিং ঠিকানা",
  'Insufficient balance': 'অপর্যাপ্ত মূল্য',
  'Most Popular': 'সবচেয়ে জনপ্রিয়',
  'Added to Wishlist': 'উইশলিস্টে যোগ করা হয়েছে',
  'Removed from Wishlist': 'উইশলিস্ট থেকে অপসারণ করা হয়েছে',
  'DELETE_ACCOUNT': 'অ্যাকাউন্ট মুছে ফেলুন'
};
