Map<String, String> english = {
  'CATEGORIES': "Categories",
  'TRENDY_COLLECTIONS': 'Trendy Collections',
  'FLASH_SALE': 'Flash Sale',
  'SEE_ALL': 'See All',
  'NEW': 'New',
  'HOME': 'Home',
  'CATEGORY': 'Category',
  'WISHLIST': 'Wishlist',
  'PROFILE': 'Profile',
  'MEN': 'Men',
  'WOMEN': 'Women',
  'KIDS': 'Kids',
  'SPORTS': 'Sports',
  'SALE_AND_OFFER': 'Sale & Offer',
  'SING_IN_TO_SEE_YOUR_INFO': 'Sing In To See Your Info',
  'Sing In': 'Sign In',
  'Sign in to continue shopping': 'Sign in to continue shopping',
  'Password': 'Password',
  'Forgot Password': 'Forgot Password',
  'Don\'t have an account?': 'Don\'t have an account?',
  'Remember me': 'Remember me',
  'Sign Up': 'Sign Up',
  'Email': 'Email',
  'Phone': 'Phone',
  '*Use Phone Instead': '*Use Phone Instead',
  '*Use Email Instead': '*Use Email Instead',
  'Name': 'Name',
  'Already have an account?': 'Already have an account?',
  'Welcome Back': 'Welcome Back',
  'Welcome Back, ': 'Welcome Back, ',
  'MY_ACCOUNT': 'My Account',
  'ORDER_HISTORY': 'Order History',
  'RETURN_ORDERS': 'Return Orders',
  'CHANGE_PASSWORD': 'Change Password',
  'EDIT_PROFILE': 'Edit Profile',
  'ADDRESSES': 'Address',
  'Terms & Conditions': 'Terms & Conditions',
  'Privacy Policy': 'Privacy Policy',
  'CONTACT_US': 'Contact Us',
  'About Us': 'About Us',
  'LOGOUT': 'Logout',
  'Cookies Policy': 'Cookies Policy',
  'Size Charts': 'Size Charts',
  'Shipping': 'Shipping',
  'Return & Exchange': 'Return & Exchange',
  'Help': 'Help',
  'TOTAL_ORDERS': 'Total Orders',
  'TOTAL_COMPLETED': 'Total Completed',
  'TOTAL_RETURNED': 'Total Returnd',
  'WALLET_BALANCE': 'Wallet Balance',
  'CHANGE_LANGUAGE': 'Change Language',
  'CHOOSE_SIZE': 'Choose Size:',
  'CHOOSE_COLOR': 'Choose Color:',
  'QUANTITY': 'Quantity:',
  'FAVORITE': 'Favorite',
  'ADD_TO_CART': 'Add To Cart',
  'SHIPPING_AND_RETURN': 'Shipping & Return',
  'REVIEW': 'Review',
  'DETAILS': 'Details',
  'PRODUCT_DTAILS': 'Product Details',
  'RELATED_PRODUCTS': 'Related Products',
  'PROFILE_IMAGE_SAVED_SUCCESSFULLY': 'Profile Image Saved Successfully',
  'SUCCESS': 'Success',
  'ERROR': 'Error',
  'Press back again to exit.': 'Press back again to exit.',
  'Home': 'Home',
  'Category': 'Category',
  'Wishlist': 'Wishlist',
  'Profile': 'Profile',
  'Address': 'Address',
  'Add New Address': 'Add New Address',
  'Full Name': 'Full Name',
  'Zip Code': 'Zip Code',
  'Street Address': 'Street Address',
  'Add Address': 'Add Address',
  'Cancel': 'Cancel',
  'Update Address': 'Update Address',
  'Are you sure you want to delete?': 'Are you sure you want to delete?',
  'Delete': 'Delete',
  'Change Password': 'Change Password',
  'Old Password': 'Old Password',
  'PLEASE_TYPE_OLD_PASSWORD': 'Please type old password',
  'PLEASE_TYPE_NEW_PASSWORD': 'Please type New password',
  'New Password': 'New Password',
  'Confirm Password': 'Confirm Password',
  'PLEASE_TYPE_CONFIRM_PASSWORD': 'Please type confirm password',
  'PASSWORD_NOT_MATCHED': 'Password not matched',
  'Save Changes': 'Save Changes',
  'Edit Profile': 'Edit Profile',
  'PLEASE_TYPE_Name': 'Please type your full name',
  'PLEASE_TYPE_EMAIL': 'Please type email',
  'PLEASE_TYPE_PHONE_NUMBER': 'Please type phone number',
  'IMAGE_SHOULD_BE_LESS_THAN_2MB': 'Image should be less then 2 MB',
  'SOMETHING_WRONG': 'Something wrong',
  'PROFILE_UPDATE_SUCCESSFULLY': 'Profile Updated Successfully',
  'PASSWORD_UPDATE_SUCCESSFULLY': 'Password Updated Successfully',
  'PLEASE_ENTER_VALID_INPUT': 'Please Enter Valid Input',
  'Verify Email': 'Verify Email',
  'Verify Number': 'Verify Number',
  'Enter OTP': 'Enter OTP',
  'If you didn\'t receive a code!': 'If you didn\'t receive a code!',
  ' Resend': ' Resend',
  'Verify': 'Verify',
  'Back to sign in': 'Back to sign in',
  'Get OTP': 'Get OTP',
  'Reset Password': 'Reset Password',
  'Password Not Matched': 'Password Not Matched',
  'Submit': 'Submit',
  'Popular Brands': 'Popular Brands',
  'Explore All Products': 'Explore All Products',
  'Empty Wishlist': 'Empty Wishlist',
  'Search': 'Search',
  'Product added to cart': 'Product added to cart',
  'Product Details': 'Product Details',
  'No Review': 'No Review',
  'No Shipping & Return Policy': 'No Shipping & Return Policy',
  'VIDEOS': 'Videos',
  'Product Videos': 'Product Videos',
  'Shipping & Return': 'Shipping & Return',
  'Product Reviews': 'Product Reviews',
  'Order Details': 'Order Details',
  'Thank You': 'Thank You',
  'Your Order status is as follows': 'Your Order status is as follows',
  'Order ID: ': 'Order ID: ',
  'Order Canceled': 'Order Canceled',
  'Order Rejected': 'Order Rejected',
  'Order ID:': 'Order ID:',
  'Order Date:': 'Order Date:',
  'Order Status:': 'Order Status:',
  'Payment Status:': 'Payment Status:',
  'Payment Type:': 'Payment Type:',
  'Pending': 'Pending',
  'Confirmed': 'Confirmed',
  'On The Way': 'On The Way',
  'Delivered': 'Delivered',
  'Cenceled': 'Cenceled',
  'Rejected': 'Rejected',
  'Paid': 'Paid',
  'Unpaid': 'Unpaid',
  'Name:': 'Name:',
  'Phone:': 'Phone:',
  'Email:': 'Email:',
  'Outlet Address:': 'Outlet Address:',
  'Shipping Address:': 'Shipping Address:',
  'Billing Address:': 'Billing Address:',
  'Order Summary': 'Order Summary',
  'Subtotal': 'Subtotal',
  'Tax': 'Tax',
  'Shipping Charge': 'Shipping Charge',
  'Discount': 'Discount',
  'Download Receipt': 'Download Receipt',
  'Return Request': 'Return Request',
  'Cancel Order': 'Cancel Order',
  'Tel:': 'Tel:',
  'Order#': 'Order#',
  'Qty': 'Qty',
  'Item Description': 'Item Description',
  'Price': 'Price',
  'Total': 'Total',
  'Order Type': 'Order Type',
  'Order Date Time': 'Order Date Time',
  'Delivery': 'Delivery',
  'Pickup': 'Pickup',
  'POS': 'POS',
  'Customer': 'Customer',
  'Powered by': 'Powered by',
  'Print Invoice': 'Print Invoice',
  'Edit Review': 'Edit Review',
  'Your Review': 'Your Review',
  'Review Details': 'Review Details',
  'Please write review details': '',
  'Upload Images': 'Upload Images',
  'Add Image': 'Add Image',
  'Submit Review': 'Submit Review',
  'Info: ': 'Info: ',
  'Product': 'Product',
  'Delivery Status: ': 'Delivery Status: ',
  'Payment Status: ': 'Payment Status: ',
  'Total: ': 'Total: ',
  'Qty:': 'Qty:',
  'Write Review': 'Write Review',
  'Price: ': 'Price: ',
  'Return Status: ': 'Return Status: ',
  'Accepted': 'Accepted',
  'Return Order Details': 'Return Order Details',
  'Return Reason': 'Return Reason',
  'Return Note': 'Return Note',
  'Attachment': 'Attachment',
  'Return Response': 'Return Response',
  'Request Return': 'Request Return',
  'Please select return reason': 'Please select return reason',
  'Please write return note': 'Please write return note',
  'Please select an item': 'Please select an item',
  'Order Canceled Successfully!': 'Order Canceled Successfully!',
  'Return request submitted successfully!':
      'Return request submitted successfully!',
  'Return request not submitted': 'Return request not submitted',
  'Review submitted successfully!': 'Review submitted successfully!',
  'Review not submitted': 'Review not submitted',
  'Review Updated successfully!': 'Review Updated successfully!',
  'Address Added Successfully!': 'Address Added Successfully!',
  'ADDRESS_UPDATED_SUCCESSFULLY': 'Address Updated Successfully!',
  'ADDRESS_DELETED_SUCCESSFULLY': 'Address Deleted Successfully!',
  'Shipping Information': 'Shipping Information',
  'Pick Up': 'Pick Up',
  'Shipping Address': 'Shipping Address',
  'Edit': 'Edit',
  'Add': 'Add',
  'Save shipping address as a billing address.':
      'Save shipping address as a billing address.',
  'Apply Promo, Coupon or Voucher': 'Apply Promo, Coupon or Voucher',
  'Coupon Applied': 'Coupon Applied',
  'Get discount with your order': 'Get discount with your order',
  'You saved': 'You saved',
  'Shipping & billing addresses are required.':
      'Shipping & billing addresses are required.',
  'Outlet is required.': 'Outlet is required.',
  'Save & Pay': 'Save & Pay',
  'Order': 'Order',
  'On the': 'On the',
  'Way': 'Way',
  'Stock is over': 'Stock is over',
  'Shopping Cart': 'Shopping Cart',
  'Your cart is empty': 'Your cart is empty',
  'Procced to Checkout': 'Procced to Checkout',
  'Shipping, Taxes & Discount Calculate at Checkout':
      'Shipping, Taxes & Discount Calculate at Checkout',
  'Remove': 'Remove',
  'Enter Code': 'Enter Code',
  'Please enter a valid coupon': 'Please enter a valid coupon',
  'Promo, Coupon or Voucher': 'Promo, Coupon or Voucher',
  'Apply': 'Apply',
  'Coupon & Vouchers for you': 'Coupon & Vouchers for you',
  'Filter & Sorting': 'Filter & Sorting',
  'Product Type': 'Product Type',
  'Size': 'Size',
  'Color': 'Color',
  'Brands': 'Brands',
  'Sort By': 'Sort By',
  'Newest': 'Newest',
  'Price Low To High': 'Price Low To High',
  'Price High To Low': 'Price High To Low',
  'Top Rated': 'Top Rated',
  'See All': 'See All',
  'Payment Information': 'Payment Information',
  'Select Payment Method': 'Select Payment Method',
  'Confirm Order': 'Confirm Order',
  'Products Found': 'Products Found',
  'Flash Sale': 'Flash Sale',
  'New': 'New',
  'Reviews': 'Reviews',
  ' Products Found': ' Products Found',
  'Validation Error.': 'Validation Error.',
  'Credentials errors.': 'Credentials errors.',
  'Invalid credentials or you are blocked':
      'Invalid credentials or you are blocked',
  'Role errors.': 'Role errors.',
  'Role does not exist.': 'Role does not exist.',
  'Login Successfully.': 'Login Successfully.',
  'Logged Out Successfully.': 'Logged Out Successfully.',
  'Invalid Api Key.': 'Invalid Api Key.',
  'User not match.': 'User not match.',
  'Something wrong.': 'Something wrong.',
  'The permission is denied.': 'The permission is denied.',
  'Product not match.': 'Product not match.',
  'The product already added in another offer. When the offer is end then you can add this item again.':
      'The product already added in another offer. When the offer is end then you can add this item again.',
  'The minimum order amount is ': 'The minimum order amount is ',
  'The coupon time is expired': 'The coupon time is expired',
  'The coupon does not exist': 'The coupon does not exist',
  'The code is invalid.': 'The code is invalid.',
  'The code is expired.': 'The code is expired.',
  'Now you can reset your password.': 'Now you can reset your password.',
  'Please check your email for the code.':
      'Please check your email for the code.',
  'Please check your phone for the code.':
      'Please check your phone for the code.',
  'The token created fail.': 'The token created fail.',
  'This email does not exist.': 'This email does not exist.',
  'This phone does not exist.': 'This phone does not exist.',
  'This User does not exist.': 'This User does not exist.',
  'This phone already exist.': 'This phone already exist.',
  'The OTP verify is successfully.': 'The OTP verify is successfully.',
  'The User verify is successfully.': 'The User verify is successfully.',
  'Register Successfully.': 'Register Successfully.',
  'Your password reset Successfully.': 'Your password reset Successfully.',
  'Select your payment method': 'Select your payment method',
  'Your payment has been successfully processed':
      'Your payment has been successfully processed',
  'The payment is canceled': 'The payment is canceled',
  'The payment gateway is disable': 'The payment gateway is disable',
  'The token saved successfully.': 'The token saved successfully.',
  'The token is invalid.': 'The token is invalid.',
  'The order already accepted.': 'The order already accepted.',
  'The order already confirmed.': 'The order already confirmed.',
  'This feature is disabled for the demo.':
      'This feature is disabled for the demo.',
  'Time slots already exist.': 'Time slots already exist.',
  'This attribute is invalid. Create attribute or attribute option.':
      'This attribute is invalid. Create attribute or attribute option.',
  'This price amount provide invalid.': 'This price amount provide invalid.',
  'This product attribute id provide invalid.':
      'This product attribute id provide invalid.',
  'This product attribute option id provide invalid.':
      'This product attribute option id provide invalid.',
  'The sku has already been taken.': 'The sku has already been taken.',
  'Cannot remove this resource permanently. It is related with another resource.':
      'Cannot remove this resource permanently. It is related with another resource.',
  'The sku field is required.': 'The sku field is required.',
  'The email or phone field is required.':
      'The email or phone field is required.',
  'The Country has already been taken.': 'The Country has already been taken.',
  'The tax field is required for all products.':
      'The tax field is required for all products.',
  'The quantity field is required for all products.':
      'The quantity field is required for all products.',
  'The product filed is required.': 'The product filed is required.',
  'The unit cost filed is required for all products.':
      'The unit cost filed is required for all products.',
  'The total product unit cost is invalid.':
      'The total product unit cost is invalid.',
  'The supplier is invalid.': 'The supplier is invalid.',
  'The status is invalid.': 'The status is invalid.',
  'The Return request already exist.': 'The Return request already exist.',
  'The last outlet can not be delete': 'The last outlet can not be delete',
  "Email Send Successfully.": "Email Send Successfully.",
  "The amount is invalid.": "The amount is invalid.",
  'Available:': 'Available:',
  'Piece': 'Piece',
  'Search Results': 'Search Results',
  'Order Type:': 'Order Type:',
  'Product Description': 'Product Description',
  'Outlet': 'Outlet',
  'Enter Valid Email Address': 'Enter Valid Email Address',
  'Thank you for your order!': 'Thank you for your order!',
  'Your order is confirmed.': 'Your order is confirmed.',
  'Go to order details': 'Go to order details',
  'YOUR_PAYMENT_HAS_BEEN_CONFIRMED': 'Your payment has been confirmed',
  'PAYMENT_FAILED': 'Payment Failed',
  'ARE_YOU_SURE_WANT_TO_CLOSE_THIS_PAYMENT_SESSION':
      'Are you sure want to close this payment session?',
  'YES_CLOSE': 'Yes',
  'RETRY': 'Retry',
  'Please select payment method.': 'Please select payment method.',
  'Billing Address': 'Billing Address',
  'Insufficient balance': 'Insufficient balance',
  'Most Popular': 'Most Popular',
  'Added to Wishlist': 'Added to Wishlist',
  'Removed from Wishlist': 'Removed from Wishlist',
  'DELETE_ACCOUNT': 'Delete Account'
};
